import type { Client } from "@/types";

export const FALLBACK_CLIENTS: Client[] = [
  {
    id: "fallback-1",
    nombre: "CEDIR",
    feeMensual: 1200000,
    nivelCarga: "Alta",
    rentabilidad: "Alta",
    estado: "Activo",
    proximaAccion: "",
  },
  {
    id: "fallback-2",
    nombre: "SEMO",
    feeMensual: 1200000,
    nivelCarga: "Alta",
    rentabilidad: "Alta",
    estado: "Activo",
    proximaAccion: "",
  },
  {
    id: "fallback-3",
    nombre: "SIPEC",
    feeMensual: 700000,
    nivelCarga: "Alta",
    rentabilidad: "Alta",
    estado: "Activo",
    proximaAccion: "",
  },
  {
    id: "fallback-4",
    nombre: "SALAS",
    feeMensual: 550000,
    nivelCarga: "Muy alta",
    rentabilidad: "Media",
    estado: "Activo",
    proximaAccion: "",
  },
  {
    id: "fallback-5",
    nombre: "Juntos",
    feeMensual: 500000,
    nivelCarga: "Media",
    rentabilidad: "Media",
    estado: "En prueba",
    proximaAccion: "",
  },
  {
    id: "fallback-6",
    nombre: "Brazos Abiertos",
    feeMensual: 450000,
    nivelCarga: "Media",
    rentabilidad: "Alta",
    estado: "Activo",
    proximaAccion: "",
  },
  {
    id: "fallback-7",
    nombre: "Manera Pérez",
    feeMensual: 350000,
    nivelCarga: "Media",
    rentabilidad: "Media",
    estado: "En prueba",
    proximaAccion: "",
  },
];
